openapi: '3.0.2'
info:
  title: Spring Rest With Restdocs
  version: '1.0'
servers:
  - url: http://localhost:8080/api/v1
paths:
  /employees:
    post:
      description: create new employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeRequest'
      responses:
        '201':
          description: employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
    get:
      description: pulls employee with details
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    put:
      description: update employee
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeRequest'
      responses:
        '200':
          description: employee updated
    delete:
      description: delete employee
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Resource deleted successfully


components:
  schemas:
    EmployeeRequest:
      type: object
      properties:
        name:
          type: string              
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string